### PR TITLE
Refactore to restful routes

### LINKED ISSUE #1: Add RESTful routes
We might have a mobile application for the platform , so the backend should have routes that can be reached by mobile clients

### PR DESCRIPTION
**Pull request by MiloudiMohamed**
This PR contains to commits:

The first commit is a fix #1 adding restful routes as well as adding the correspond controllers
There some exceptions due to how the code was written so I just changed the method name on the controller (eg: `sendMail => send`)
I didn't change code all method login stays the same

The second commit is a code refactoring for the `ManageHackersController.php`, getting rid of some unnecessary code (using `eloquent` and `relations` power instead of the `DB` facade)

Also I have deleted this part of the method
```php
$Hackers_v2 =Hacker::all() ;
$now = Carbon::now();
$limit = 2 ;
foreach ($Hackers_v2 as $hacker ) {
    $recieved_date = Carbon::parse($hacker->accepted_email_received_at)->addDays($limit) ; 
    if($recieved_date->lt($now)) {
        $hacker->reject();
        $hacker->save();
    }       
}
```

which first it not a good idea to make a loop each time you land on the page (eg: for more than 1000 member)

secondly the code itself doesn't do anything

explanation:
imagine accepted_email_received_at = 13/04/2019 and I'm accepted (`decision`) and we are on the same date so nothing is happens
but after 3 day from now I will be automatically rejected due to this code 

**PS: this is as far as I understood the code**

Some other function also need some refactor so I it'll not bother you I'll submit some refactors from time to time

In the end Thank you for this great idea which facilitate the process of organizing a hackathon

### CODE REVIEW

**Comment by SalahEddineBC** [comment]
please include some tests 🚀

**Comment by AdelNamani** [comment]
Hi Mohamed , thank's for being the first contributor to our project and for tips you gave us through your changes in our code . The changes you did were great , but after testing some functionalities I've discovered that joining a team in registration is not working , would you review that again ? And this time pull to the dev branch that we've just created please .

And about the part of method you've deleted , you are right the code does nothing but it was supposed to reject hackers who haven't confirmed their attendance within 3 days after being accepted ( we've forgot the condition :/ ) , if you have a better solution for that , share it with us !

**Comment by MiloudiMohamed** [comment]
Hi, @SalahEddineBC I really don't know what to write a test for, I just refactored the code, I think it would be enough to re-run the existing tests

and for the failing test, I just ran the test suit on the master branch and it fails (`testRegisterWithoutTeam`) @AdelNamani , I don't think it's because the refactor, please re-check and let me know I may accidentally did something and didn't pay attention

**Comment by zeabdelkhalek** [comment]
Here are the errors we have found : 

- in `TeamController.php` add `use App\Http\Requests\CheckCodeRequest;`
- in `TeamController.php` add `use Illuminate\Support\Facades\DB;`
- in `RegisterController.php` add `use Illuminate\Support\Facades\Crypt;`
- in `web.php` change line 30 to `Route::get('/register/confirm/{token}','Hacker\RegisterController@update')->name('confirm');`

**Don't forget to pull in the dev branch this time ! Thank's again**

**Comment by MiloudiMohamed** [comment]
@AbdelkhalekESI nice catches! I have add them as you mentioned

**Comment by AdelNamani** [comment]
Your pull request in dev branch is merged ! thank's for your contribution .

**Pull request closed without merging**
