### PR TITLE
Dockerizing LaraHack

### PR DESCRIPTION
**Pull request by th3happybit**
Dockerizing LaraHack
- adding app Dockerfile image
- adding docker-compose file to manage the services (mysql, redis, nginx)
- adding services config files

### CODE REVIEW

**Comment by zeabdelkhalek** [comment]
@th3happybit  what's the status on this PR ?

**Comment by th3happybit** [comment]
> @th3happybit what's the status on this PR ?

There is something wrong in it, with storage permissions and its need more testing, and this is why i cancelled, i'm working on new stable one, i will submit it in few days

**Comment by th3happybit** [comment]
@AbdelkhalekESI  Problems have been resolved with the latest version, you can now review this PR, 
and i can make a new PR in your dev:branch if you want

**Comment by zeabdelkhalek** [comment]
we couldn't get the app running using steps that you mentioned , we are facing this error:
``` *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: .... ```  
in the webserver service.
please can you look for the cause ? or maybe guide us to make it running , it would be better to copy everthing to the container to avoid fixing permissions which may lead to errors.
and we have a warning we'd like to solve it which is using Dusk which is unsafe to use in production.

**Comment by th3happybit** [comment]
> we couldn't get the app running using steps that you mentioned , we are facing this error:
> `*1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: ....`
> in the webserver service.
> please can you look for the cause ? or maybe guide us to make it running , it would be better to copy everthing to the container to avoid fixing permissions which may lead to errors.
> and we have a warning we'd like to solve it which is using Dusk which is unsafe to use in production.

of course i will try to find the cause

**Pull request closed without merging**
